export const PRODUCT_LIST_TABLE = 'product_list'

export const DAILY_WORK_ROW_COLUMNS = [
  'id',
  'initial',
  'company',
  'place',
  'area',
  'work_type',
  'head',
  'hole',
  'inch',
  'hold',
  'worker_t',
  'worker_t_time',
  'worker_t_time_final',
  'marking_weld_a_started_on',
  'marking_weld_a_completed_on',
  'worker_main',
  'worker_main_time',
  'worker_main_time_final',
  'main_started_on',
  'main_completed_on',
  'worker_nasa',
  'worker_nasa_time',
  'worker_nasa_time_final',
  'nasa_started_on',
  'nasa_completed_on',
  'worker_welding',
  'worker_welding_time',
  'worker_welding_time_final',
  'welding_started_on',
  'welding_completed_on',
].join(',')

export const DAILY_WORK_TABS = [
  {
    key: 'branch',
    label: '가지관',
    qtyField: 'head',
    qtyUnit: '헤드',
    showInch: false,
    statusField: 'worker_t',
    startedField: 'marking_weld_a_started_on',
    completedField: 'marking_weld_a_completed_on',
    completedTimeField: 'worker_t_time',
    completedFinalTimeField: 'worker_t_time_final',
    accent: 'emerald',
  },
  {
    key: 'main',
    label: '메인관',
    qtyField: 'hole',
    qtyUnit: '홀',
    showInch: false,
    statusField: 'worker_main',
    startedField: 'main_started_on',
    completedField: 'main_completed_on',
    completedTimeField: 'worker_main_time',
    completedFinalTimeField: 'worker_main_time_final',
    accent: 'cyan',
  },
  {
    key: 'nasa',
    label: '나사',
    qtyField: 'head',
    qtyUnit: '헤드',
    showInch: false,
    statusField: 'worker_nasa',
    startedField: 'nasa_started_on',
    completedField: 'nasa_completed_on',
    completedTimeField: 'worker_nasa_time',
    completedFinalTimeField: 'worker_nasa_time_final',
    accent: 'amber',
  },
  {
    key: 'welding',
    label: '용접',
    qtyField: 'head',
    qtyUnit: '헤드',
    showInch: true,
    statusField: 'worker_welding',
    startedField: 'welding_started_on',
    completedField: 'welding_completed_on',
    completedTimeField: 'worker_welding_time',
    completedFinalTimeField: 'worker_welding_time_final',
    accent: 'violet',
  },
]

export function getTabByKey(key) {
  return DAILY_WORK_TABS.find((tab) => tab.key === key) ?? DAILY_WORK_TABS[0]
}
