export const SHIPMENT_SPEC_DIALOG_LOCALES = [
  { value: 'ko', label: '한국어' },
  { value: 'th', label: 'ภาษาไทย' },
]

const COPY = {
  ko: {
    portrait: '세로',
    landscape: '가로',
    close: '닫기',
    print: '인쇄',
    printAll: '전체 인쇄',
    add: '+',
    remove: '−',
    printer: '프린터',
    refresh: '새로고침',
    loading: '불러오는 중',
    defaultPrinter: '시스템 기본 프린터',
    defaultSuffix: ' (기본)',
    printerLoadError: '프린터 목록을 불러오지 못했습니다.',
    saveFailed: '저장 실패',
    drawing: '도번',
    company: '회사명',
    place: '현장명',
    area: '구역명',
    historyTitle: '출력됨',
    historyHelp: '삭제는 되고 수정은 안 됩니다.',
    nextTitle: '이번 출력',
    nextHelp: '이번에 출력할 내용만 입력하세요.',
    nextPlaceholder: '출력할 내용을 입력하세요',
  },
  th: {
    portrait: 'แนวตั้ง',
    landscape: 'แนวนอน',
    close: 'ปิด',
    print: 'พิมพ์',
    printAll: 'พิมพ์ทั้งหมด',
    add: '+',
    remove: '−',
    printer: 'เครื่องพิมพ์',
    refresh: 'รีเฟรช',
    loading: 'กำลังโหลด',
    defaultPrinter: 'เครื่องพิมพ์เริ่มต้นของระบบ',
    defaultSuffix: ' (ค่าเริ่มต้น)',
    printerLoadError: 'โหลดรายการเครื่องพิมพ์ไม่สำเร็จ',
    saveFailed: 'บันทึกไม่สำเร็จ',
    drawing: 'หมายเลขแบบ',
    company: 'บริษัท',
    place: 'ไซต์งาน',
    area: 'โซน',
    historyTitle: 'พิมพ์แล้ว',
    historyHelp: 'ลบได้ แต่แก้ไม่ได้',
    nextTitle: 'พิมพ์ครั้งนี้',
    nextHelp: 'กรอกเฉพาะรายการที่ต้องการพิมพ์เพิ่ม',
    nextPlaceholder: 'กรอกรายการที่จะพิมพ์',
  },
}

export const getShipmentSpecDialogCopy = (locale) => COPY[locale] ?? COPY.th
