ALTER TABLE public.cnc_items
  ADD COLUMN IF NOT EXISTS company text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS place text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS area text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS drawing_no text NOT NULL DEFAULT '';
