CREATE TABLE IF NOT EXISTS public.inventory_material_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category text NOT NULL CHECK (category IN ('pipe', 'fitting')),
  material_group text NOT NULL DEFAULT '',
  name text NOT NULL,
  spec text NOT NULL,
  unit text NOT NULL DEFAULT '본',
  sort_order integer NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT inventory_material_items_unique_key UNIQUE (category, material_group, name, spec)
);

CREATE TABLE IF NOT EXISTS public.inventory_transactions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  transaction_date date NOT NULL DEFAULT CURRENT_DATE,
  transaction_type text NOT NULL CHECK (transaction_type IN ('incoming', 'return', 'use', 'adjustment')),
  company_id bigint REFERENCES public.company_list(id) ON DELETE RESTRICT,
  company_name text NOT NULL DEFAULT '',
  place_name text NOT NULL DEFAULT '',
  memo text NOT NULL DEFAULT '',
  manufacturer text NOT NULL DEFAULT '',
  supplier text NOT NULL DEFAULT '',
  created_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.inventory_transaction_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  transaction_id bigint NOT NULL REFERENCES public.inventory_transactions(id) ON DELETE CASCADE,
  material_item_id bigint NOT NULL REFERENCES public.inventory_material_items(id) ON DELETE RESTRICT,
  quantity numeric(12, 2) NOT NULL CHECK (quantity <> 0),
  note text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS inventory_material_items_category_idx
  ON public.inventory_material_items (category, material_group, sort_order);

CREATE INDEX IF NOT EXISTS inventory_transactions_date_idx
  ON public.inventory_transactions (transaction_date DESC);

CREATE INDEX IF NOT EXISTS inventory_transactions_company_idx
  ON public.inventory_transactions (company_id);

CREATE INDEX IF NOT EXISTS inventory_transaction_items_transaction_idx
  ON public.inventory_transaction_items (transaction_id);

CREATE INDEX IF NOT EXISTS inventory_transaction_items_material_idx
  ON public.inventory_transaction_items (material_item_id);

ALTER TABLE public.inventory_material_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_transaction_items ENABLE ROW LEVEL SECURITY;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.inventory_material_items TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.inventory_transactions TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.inventory_transaction_items TO authenticated;

GRANT USAGE, SELECT ON SEQUENCE public.inventory_material_items_id_seq TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.inventory_transactions_id_seq TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.inventory_transaction_items_id_seq TO authenticated;

DROP POLICY IF EXISTS "inventory_material_items_select_authenticated" ON public.inventory_material_items;
CREATE POLICY "inventory_material_items_select_authenticated"
ON public.inventory_material_items
FOR SELECT
TO authenticated
USING (true);

DROP POLICY IF EXISTS "inventory_material_items_manage_authenticated" ON public.inventory_material_items;
CREATE POLICY "inventory_material_items_manage_authenticated"
ON public.inventory_material_items
FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);

DROP POLICY IF EXISTS "inventory_transactions_select_authenticated" ON public.inventory_transactions;
CREATE POLICY "inventory_transactions_select_authenticated"
ON public.inventory_transactions
FOR SELECT
TO authenticated
USING (true);

DROP POLICY IF EXISTS "inventory_transactions_manage_authenticated" ON public.inventory_transactions;
CREATE POLICY "inventory_transactions_manage_authenticated"
ON public.inventory_transactions
FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);

DROP POLICY IF EXISTS "inventory_transaction_items_select_authenticated" ON public.inventory_transaction_items;
CREATE POLICY "inventory_transaction_items_select_authenticated"
ON public.inventory_transaction_items
FOR SELECT
TO authenticated
USING (true);

DROP POLICY IF EXISTS "inventory_transaction_items_manage_authenticated" ON public.inventory_transaction_items;
CREATE POLICY "inventory_transaction_items_manage_authenticated"
ON public.inventory_transaction_items
FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);

INSERT INTO public.inventory_material_items (category, material_group, name, spec, unit, sort_order)
VALUES
  ('pipe', '일반강관', '일반강관', '25', '본', 100),
  ('pipe', '일반강관', '일반강관', '32', '본', 110),
  ('pipe', '일반강관', '일반강관', '40', '본', 120),
  ('pipe', '일반강관', '일반강관', '50', '본', 130),
  ('pipe', '일반강관', '일반강관', '65', '본', 140),
  ('pipe', '일반강관', '일반강관', '80', '본', 150),
  ('pipe', '일반강관', '일반강관', '100', '본', 160),
  ('pipe', '일반강관', '일반강관', '125', '본', 170),
  ('pipe', '일반강관', '일반강관', '150', '본', 180),
  ('pipe', '일반강관', '일반강관', '200', '본', 190),
  ('pipe', '스케쥴', '스케쥴', '100', '본', 300),
  ('pipe', '스케쥴', '스케쥴', '125', '본', 310),
  ('pipe', '스케쥴', '스케쥴', '150', '본', 320)
ON CONFLICT (category, material_group, name, spec) DO UPDATE
SET
  unit = EXCLUDED.unit,
  sort_order = EXCLUDED.sort_order,
  is_active = true,
  updated_at = now();
