CREATE TABLE IF NOT EXISTS public.employee_option_settings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category text NOT NULL CHECK (category IN ('department', 'assigned_department', 'nationality')),
  value text NOT NULL,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT employee_option_settings_category_value_key UNIQUE (category, value)
);

ALTER TABLE public.employee_option_settings ENABLE ROW LEVEL SECURITY;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.employee_option_settings TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.employee_option_settings_id_seq TO authenticated;

DROP POLICY IF EXISTS "employee_option_settings_select_authenticated" ON public.employee_option_settings;
CREATE POLICY "employee_option_settings_select_authenticated"
ON public.employee_option_settings
FOR SELECT
TO authenticated
USING (true);

DROP POLICY IF EXISTS "employee_option_settings_admin_insert" ON public.employee_option_settings;
CREATE POLICY "employee_option_settings_admin_insert"
ON public.employee_option_settings
FOR INSERT
TO authenticated
WITH CHECK (
  EXISTS (
    SELECT 1
    FROM public.profiles
    WHERE profiles.id = auth.uid()
      AND profiles.role = 'admin'
  )
);

DROP POLICY IF EXISTS "employee_option_settings_admin_update" ON public.employee_option_settings;
CREATE POLICY "employee_option_settings_admin_update"
ON public.employee_option_settings
FOR UPDATE
TO authenticated
USING (
  EXISTS (
    SELECT 1
    FROM public.profiles
    WHERE profiles.id = auth.uid()
      AND profiles.role = 'admin'
  )
)
WITH CHECK (
  EXISTS (
    SELECT 1
    FROM public.profiles
    WHERE profiles.id = auth.uid()
      AND profiles.role = 'admin'
  )
);

DROP POLICY IF EXISTS "employee_option_settings_admin_delete" ON public.employee_option_settings;
CREATE POLICY "employee_option_settings_admin_delete"
ON public.employee_option_settings
FOR DELETE
TO authenticated
USING (
  EXISTS (
    SELECT 1
    FROM public.profiles
    WHERE profiles.id = auth.uid()
      AND profiles.role = 'admin'
  )
);

INSERT INTO public.employee_option_settings (category, value, sort_order)
VALUES
  ('department', '생산부', 0),
  ('department', '용접부', 1),
  ('department', '나사부', 2),
  ('department', 'CNC', 3),
  ('department', '지게차', 4),
  ('assigned_department', '메인관', 0),
  ('assigned_department', '가지관', 1),
  ('assigned_department', '치부', 2),
  ('assigned_department', '포장', 3),
  ('assigned_department', '용접', 4),
  ('assigned_department', '나사', 5),
  ('assigned_department', 'CNC', 6),
  ('assigned_department', '페인트', 7),
  ('assigned_department', '지게차', 8),
  ('nationality', '한국', 0),
  ('nationality', '중국', 1),
  ('nationality', '태국', 2),
  ('nationality', '러시아', 3),
  ('nationality', '파키스탄', 4)
ON CONFLICT (category, value) DO UPDATE
SET sort_order = EXCLUDED.sort_order;
