ALTER TABLE public.inventory_material_items
  ADD COLUMN IF NOT EXISTS material_type text NOT NULL DEFAULT 'raw' CHECK (material_type IN ('raw', 'subsidiary')),
  ADD COLUMN IF NOT EXISTS is_default boolean NOT NULL DEFAULT false;

UPDATE public.inventory_material_items
SET material_type = 'raw',
    is_default = true,
    updated_at = now()
WHERE material_type = 'raw';

ALTER TABLE public.inventory_material_items
  DROP CONSTRAINT IF EXISTS inventory_material_items_unique_key;

CREATE UNIQUE INDEX IF NOT EXISTS inventory_material_items_type_unique_idx
  ON public.inventory_material_items (category, material_type, material_group, name, spec);

CREATE INDEX IF NOT EXISTS inventory_material_items_type_default_idx
  ON public.inventory_material_items (material_type, is_default, sort_order);

ALTER TABLE public.inventory_transactions
  ADD COLUMN IF NOT EXISTS material_type text NOT NULL DEFAULT 'raw' CHECK (material_type IN ('raw', 'subsidiary'));

UPDATE public.inventory_transactions
SET material_type = 'raw',
    updated_at = now()
WHERE material_type = 'raw';

CREATE INDEX IF NOT EXISTS inventory_transactions_company_type_date_idx
  ON public.inventory_transactions (company_id, material_type, transaction_date DESC);

CREATE TABLE IF NOT EXISTS public.inventory_company_material_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id bigint NOT NULL REFERENCES public.company_list(id) ON DELETE CASCADE,
  material_item_id bigint NOT NULL REFERENCES public.inventory_material_items(id) ON DELETE CASCADE,
  material_type text NOT NULL DEFAULT 'raw' CHECK (material_type IN ('raw', 'subsidiary')),
  sort_order integer NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT inventory_company_material_items_unique_key UNIQUE (company_id, material_item_id)
);

COMMENT ON TABLE public.inventory_material_items IS '입출고에서 사용하는 전체 자재 품목 원장입니다. 원자재/부자재 공통 품목을 한 번만 등록합니다.';
COMMENT ON COLUMN public.inventory_material_items.id IS '자재 품목 고유 ID입니다. 입출고 수량과 회사별 품목 설정에서 이 값을 참조합니다.';
COMMENT ON COLUMN public.inventory_material_items.category IS '자재 큰 분류입니다. pipe는 원자재 관류, fitting은 부자재 부속류입니다.';
COMMENT ON COLUMN public.inventory_material_items.material_type IS '입출고 탭 구분입니다. raw는 원자재, subsidiary는 부자재입니다.';
COMMENT ON COLUMN public.inventory_material_items.material_group IS '표 상단에 묶어서 표시할 품목 그룹명입니다. 예: 일반강관, 스케쥴, 백엘보(용접).';
COMMENT ON COLUMN public.inventory_material_items.name IS '품목명입니다. 현재는 그룹명과 동일하게 사용합니다.';
COMMENT ON COLUMN public.inventory_material_items.spec IS '규격입니다. 예: 25, 100, 25 A, 50A*25A.';
COMMENT ON COLUMN public.inventory_material_items.unit IS '단위입니다. 예: 본, 개.';
COMMENT ON COLUMN public.inventory_material_items.sort_order IS '화면과 엑셀 처리에서 품목을 표시하는 순서입니다.';
COMMENT ON COLUMN public.inventory_material_items.is_active IS '품목 사용 여부입니다. false이면 화면 목록에서 제외합니다.';
COMMENT ON COLUMN public.inventory_material_items.is_default IS '회사에 처음 적용할 기본 품목인지 여부입니다.';

COMMENT ON TABLE public.inventory_company_material_items IS '회사/현장별로 사용하는 자재 품목 연결표입니다. company_list의 현장마다 어떤 원자재/부자재를 쓰는지 저장합니다.';
COMMENT ON COLUMN public.inventory_company_material_items.id IS '회사별 품목 연결 고유 ID입니다.';
COMMENT ON COLUMN public.inventory_company_material_items.company_id IS 'company_list.id입니다. 회사명 + 현장명을 가진 현장 한 건을 의미합니다.';
COMMENT ON COLUMN public.inventory_company_material_items.material_item_id IS 'inventory_material_items.id입니다. 실제 자재 품목 원장을 참조합니다.';
COMMENT ON COLUMN public.inventory_company_material_items.material_type IS '입출고 탭 구분입니다. raw는 원자재, subsidiary는 부자재입니다.';
COMMENT ON COLUMN public.inventory_company_material_items.sort_order IS '해당 회사/현장에서 품목을 표시하는 순서입니다. 기본값은 품목 원장의 순서를 복사합니다.';
COMMENT ON COLUMN public.inventory_company_material_items.is_active IS '해당 회사/현장에서 이 품목을 사용하는지 여부입니다. false이면 그 회사 화면에서 제외합니다.';
COMMENT ON COLUMN public.inventory_company_material_items.created_at IS '회사별 품목 연결이 생성된 시각입니다.';
COMMENT ON COLUMN public.inventory_company_material_items.updated_at IS '회사별 품목 연결이 마지막으로 수정된 시각입니다.';

COMMENT ON TABLE public.inventory_transactions IS '입출고 내역의 행 헤더입니다. 날짜, 현장, 내역, 제조사, 입고처/출고처를 저장합니다.';
COMMENT ON COLUMN public.inventory_transactions.material_type IS '입출고 내역의 탭 구분입니다. raw는 원자재, subsidiary는 부자재입니다.';

COMMENT ON TABLE public.inventory_transaction_items IS '입출고 내역 한 행에 입력된 자재별 수량입니다.';
COMMENT ON COLUMN public.inventory_transaction_items.material_item_id IS 'inventory_material_items.id입니다. 어떤 자재 품목의 수량인지 나타냅니다.';
COMMENT ON COLUMN public.inventory_transaction_items.quantity IS '입출고 수량입니다. 양수는 입고, 음수는 출고/반출로 집계합니다.';

CREATE INDEX IF NOT EXISTS inventory_company_material_items_company_type_idx
  ON public.inventory_company_material_items (company_id, material_type, is_active, sort_order);

ALTER TABLE public.inventory_company_material_items ENABLE ROW LEVEL SECURITY;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.inventory_company_material_items TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.inventory_company_material_items_id_seq TO authenticated;

DROP POLICY IF EXISTS "inventory_company_material_items_select_authenticated" ON public.inventory_company_material_items;
CREATE POLICY "inventory_company_material_items_select_authenticated"
ON public.inventory_company_material_items
FOR SELECT
TO authenticated
USING (true);

DROP POLICY IF EXISTS "inventory_company_material_items_manage_authenticated" ON public.inventory_company_material_items;
CREATE POLICY "inventory_company_material_items_manage_authenticated"
ON public.inventory_company_material_items
FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);

INSERT INTO public.inventory_material_items
  (category, material_type, material_group, name, spec, unit, sort_order, is_active, is_default)
VALUES
  ('pipe', 'raw', '일반강관', '일반강관', '20', '본', 90, true, true),
  ('pipe', 'raw', '일반강관', '일반강관', '25', '본', 100, true, true),
  ('pipe', 'raw', '일반강관', '일반강관', '32', '본', 110, true, true),
  ('pipe', 'raw', '일반강관', '일반강관', '40', '본', 120, true, true),
  ('pipe', 'raw', '일반강관', '일반강관', '50', '본', 130, true, true),
  ('pipe', 'raw', '일반강관', '일반강관', '65', '본', 140, true, true),
  ('pipe', 'raw', '일반강관', '일반강관', '80', '본', 150, true, true),
  ('pipe', 'raw', '일반강관', '일반강관', '100', '본', 160, true, true),
  ('pipe', 'raw', '일반강관', '일반강관', '125', '본', 170, true, true),
  ('pipe', 'raw', '일반강관', '일반강관', '150', '본', 180, true, true),
  ('pipe', 'raw', '일반강관', '일반강관', '200', '본', 190, true, true),
  ('pipe', 'raw', '스케쥴', '스케쥴', '100', '본', 300, true, true),
  ('pipe', 'raw', '스케쥴', '스케쥴', '125', '본', 310, true, true),
  ('pipe', 'raw', '스케쥴', '스케쥴', '150', '본', 320, true, true)
ON CONFLICT (category, material_type, material_group, name, spec)
DO UPDATE SET
  unit = EXCLUDED.unit,
  sort_order = EXCLUDED.sort_order,
  is_active = true,
  is_default = true,
  updated_at = now();

INSERT INTO public.inventory_material_items
  (category, material_type, material_group, name, spec, unit, sort_order, is_active, is_default)
VALUES
  ('fitting', 'subsidiary', '백엘보(용접)', '백엘보(용접)', '25 A', '개', 1000, true, true),
  ('fitting', 'subsidiary', '백엘보(용접)', '백엘보(용접)', '32 A', '개', 1010, true, true),
  ('fitting', 'subsidiary', '백엘보(용접)', '백엘보(용접)', '40 A', '개', 1020, true, true),
  ('fitting', 'subsidiary', '백엘보(용접)', '백엘보(용접)', '50 A', '개', 1030, true, true),
  ('fitting', 'subsidiary', '백엘보(용접)', '백엘보(용접)', '65 A', '개', 1040, true, true),
  ('fitting', 'subsidiary', '백엘보(용접)', '백엘보(용접)', '80 A', '개', 1050, true, true),
  ('fitting', 'subsidiary', '백엘보(용접)', '백엘보(용접)', '100 A', '개', 1060, true, true),
  ('fitting', 'subsidiary', '백엘보(용접)', '백엘보(용접)', '125 A', '개', 1070, true, true),
  ('fitting', 'subsidiary', '백엘보(용접)', '백엘보(용접)', '150 A', '개', 1080, true, true),
  ('fitting', 'subsidiary', '백티이(용접)', '백티이(용접)', '25 A', '개', 1100, true, true),
  ('fitting', 'subsidiary', '백티이(용접)', '백티이(용접)', '32 A', '개', 1110, true, true),
  ('fitting', 'subsidiary', '백티이(용접)', '백티이(용접)', '40 A', '개', 1120, true, true),
  ('fitting', 'subsidiary', '백티이(용접)', '백티이(용접)', '50 A', '개', 1130, true, true),
  ('fitting', 'subsidiary', '백티이(용접)', '백티이(용접)', '65 A', '개', 1140, true, true),
  ('fitting', 'subsidiary', '백티이(용접)', '백티이(용접)', '80 A', '개', 1150, true, true),
  ('fitting', 'subsidiary', '백티이(용접)', '백티이(용접)', '100 A', '개', 1160, true, true),
  ('fitting', 'subsidiary', '백티이(용접)', '백티이(용접)', '125 A', '개', 1170, true, true),
  ('fitting', 'subsidiary', '백티이(용접)', '백티이(용접)', '150 A', '개', 1180, true, true),
  ('fitting', 'subsidiary', '백레듀샤(용접)', '백레듀샤(용접)', '50A*25A', '개', 1200, true, true),
  ('fitting', 'subsidiary', '백레듀샤(용접)', '백레듀샤(용접)', '65A*25A', '개', 1210, true, true),
  ('fitting', 'subsidiary', '백레듀샤(용접)', '백레듀샤(용접)', '65A*32A', '개', 1220, true, true),
  ('fitting', 'subsidiary', '백레듀샤(용접)', '백레듀샤(용접)', '100A*65A', '개', 1230, true, true),
  ('fitting', 'subsidiary', '백레듀샤(용접)', '백레듀샤(용접)', '125A*65A', '개', 1240, true, true),
  ('fitting', 'subsidiary', '백레듀샤(용접)', '백레듀샤(용접)', '125A*80A', '개', 1250, true, true),
  ('fitting', 'subsidiary', '백레듀샤(용접)', '백레듀샤(용접)', '150A*65A', '개', 1260, true, true),
  ('fitting', 'subsidiary', '백레듀샤(용접)', '백레듀샤(용접)', '150A*80A', '개', 1270, true, true),
  ('fitting', 'subsidiary', '백레듀샤(용접)', '백레듀샤(용접)', '150A*100A', '개', 1280, true, true),
  ('fitting', 'subsidiary', '백엘보(나사)', '백엘보(나사)', '25 A', '개', 1300, true, true),
  ('fitting', 'subsidiary', '백엘보(나사)', '백엘보(나사)', '32 A', '개', 1310, true, true),
  ('fitting', 'subsidiary', '백엘보(나사)', '백엘보(나사)', '40 A', '개', 1320, true, true),
  ('fitting', 'subsidiary', '백엘보(나사)', '백엘보(나사)', '50 A', '개', 1330, true, true),
  ('fitting', 'subsidiary', '백티이(나사)', '백티이(나사)', '25A*25A', '개', 1400, true, true),
  ('fitting', 'subsidiary', '백티이(나사)', '백티이(나사)', '32A*25A', '개', 1410, true, true),
  ('fitting', 'subsidiary', '백티이(나사)', '백티이(나사)', '32A*32A', '개', 1420, true, true),
  ('fitting', 'subsidiary', '백티이(나사)', '백티이(나사)', '40A*25A', '개', 1430, true, true),
  ('fitting', 'subsidiary', '백티이(나사)', '백티이(나사)', '40A*32A', '개', 1440, true, true),
  ('fitting', 'subsidiary', '백티이(나사)', '백티이(나사)', '40A*40A', '개', 1450, true, true),
  ('fitting', 'subsidiary', '백티이(나사)', '백티이(나사)', '50A*25A', '개', 1460, true, true),
  ('fitting', 'subsidiary', '백티이(나사)', '백티이(나사)', '50A*32A', '개', 1470, true, true),
  ('fitting', 'subsidiary', '백티이(나사)', '백티이(나사)', '50A*50A', '개', 1480, true, true),
  ('fitting', 'subsidiary', '백레듀샤(나사)', '백레듀샤(나사)', '32A*25A', '개', 1500, true, true),
  ('fitting', 'subsidiary', '백레듀샤(나사)', '백레듀샤(나사)', '40A*25A', '개', 1510, true, true),
  ('fitting', 'subsidiary', '백레듀샤(나사)', '백레듀샤(나사)', '40A*32A', '개', 1520, true, true),
  ('fitting', 'subsidiary', '백레듀샤(나사)', '백레듀샤(나사)', '50A*25A', '개', 1530, true, true),
  ('fitting', 'subsidiary', '백레듀샤(나사)', '백레듀샤(나사)', '50A*32A', '개', 1540, true, true),
  ('fitting', 'subsidiary', '백레듀샤(나사)', '백레듀샤(나사)', '50A*40A', '개', 1550, true, true),
  ('fitting', 'subsidiary', '주물소켓', '주물소켓', '25 A', '개', 1600, true, true),
  ('fitting', 'subsidiary', '주물소켓', '주물소켓', '32 A', '개', 1610, true, true),
  ('fitting', 'subsidiary', '주물소켓', '주물소켓', '40 A', '개', 1620, true, true),
  ('fitting', 'subsidiary', '주물소켓', '주물소켓', '50 A', '개', 1630, true, true),
  ('fitting', 'subsidiary', '나사캡', '나사캡', '25 A', '개', 1700, true, true),
  ('fitting', 'subsidiary', '나사캡', '나사캡', '32 A', '개', 1710, true, true),
  ('fitting', 'subsidiary', '나사캡', '나사캡', '40 A', '개', 1720, true, true),
  ('fitting', 'subsidiary', '나사캡', '나사캡', '50 A', '개', 1730, true, true),
  ('fitting', 'subsidiary', '플렌지', '플렌지', '65 A', '개', 1800, true, true),
  ('fitting', 'subsidiary', '플렌지', '플렌지', '80 A', '개', 1810, true, true),
  ('fitting', 'subsidiary', '플렌지', '플렌지', '100 A', '개', 1820, true, true),
  ('fitting', 'subsidiary', '플렌지', '플렌지', '125 A', '개', 1830, true, true),
  ('fitting', 'subsidiary', '플렌지', '플렌지', '150 A', '개', 1840, true, true),
  ('fitting', 'subsidiary', 'FL', 'FL', '25 A', '개', 1900, true, true)
ON CONFLICT (category, material_type, material_group, name, spec)
DO UPDATE SET
  unit = EXCLUDED.unit,
  sort_order = EXCLUDED.sort_order,
  is_active = true,
  is_default = true,
  updated_at = now();
