-- Daily snapshot table + scheduler (Supabase pg_cron)
-- Run this SQL once in Supabase SQL Editor.

create table if not exists public.daily_plan_snapshots (
  id bigint generated by default as identity primary key,
  snapshot_date date not null unique,
  test_date text not null,
  weekday text not null,
  daily_target_head integer not null default 0,
  completed_head integer not null default 0,
  total_head integer not null default 0,
  remaining_head integer not null default 0,
  today_overtime_sec integer not null default 0,
  weekly_overtime_sec integer not null default 0,
  distributed_drawing_count integer not null default 0,
  total_drawing_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.capture_daily_plan_snapshot(p_snapshot_date date default ((now() at time zone 'Asia/Seoul')::date - 1))
returns void
language plpgsql
security definer
as $$
declare
  v_test_date text;
  v_weekday text;
  v_head_time_sec numeric := 80;
  v_hole_time_sec numeric := 80;
  v_daily_target_head integer := 0;
  v_completed_head integer := 0;
  v_total_head integer := 0;
  v_remaining_head integer := 0;
  v_today_overtime_sec integer := 0;
  v_weekly_overtime_sec integer := 0;
  v_distributed_drawing_count integer := 0;
  v_total_drawing_count integer := 0;
  v_workdays_for_plan integer := 1;
  v_pending_delay_sec numeric := 0;
  v_weighted_process_sec_sum numeric := 0;
  v_avg_process_sec numeric := 80;
  v_required_today_sec numeric := 0;
  v_required_week_sec numeric := 0;
  v_regular_week_sec numeric := 0;
  v_overtime_need_week_sec numeric := 0;
  v_weekday_overtime_capacity numeric := 0;
begin
  v_test_date := to_char(p_snapshot_date, 'YYYY"년 "MM"월 "DD"일');
  v_weekday := case extract(isodow from p_snapshot_date)
    when 1 then '월'
    when 2 then '화'
    when 3 then '수'
    when 4 then '목'
    when 5 then '금'
    when 6 then '토'
    else '일'
  end;

  select
    coalesce(nullif(head_time, 0), 80),
    coalesce(nullif(hole_time, 0), 80)
  into v_head_time_sec, v_hole_time_sec
  from public.setting
  limit 1;

  with source_rows as (
    select
      work_type,
      coalesce(head, 0)::numeric as head_qty,
      coalesce(hole, 0)::numeric as hole_qty,
      coalesce(delay_time, 0)::numeric as delay_time_sec,
      coalesce(drawing_date, '') as drawing_date,
      coalesce(virtual_drawing_distributed, false) as virtual_drawing_distributed,
      coalesce(marking_weld_a_status, '없음') as marking_weld_a_status,
      coalesce(marking_weld_b_status, '없음') as marking_weld_b_status,
      coalesce(marking_laser_1_status, '없음') as marking_laser_1_status,
      coalesce(marking_laser_2_status, '없음') as marking_laser_2_status,
      coalesce(nasa_status, '없음') as nasa_status,
      coalesce(beveling_status, '없음') as beveling_status,
      coalesce(main_status, '없음') as main_status
    from public.product_list
    where test_date = v_test_date
  ),
  normalized as (
    select
      *,
      replace(coalesce(work_type, ''), ' ', '') as work_type_norm,
      case
        when replace(coalesce(work_type, ''), ' ', '') like '%전실/입상%'
          or replace(coalesce(work_type, ''), ' ', '') like '%전실입상%'
        then hole_qty
        else head_qty
      end as plan_qty,
      case
        when replace(coalesce(work_type, ''), ' ', '') like '%전실/입상%'
          or replace(coalesce(work_type, ''), ' ', '') like '%전실입상%'
        then v_hole_time_sec
        else v_head_time_sec
      end as process_sec,
      (length(trim(drawing_date)) > 0 or virtual_drawing_distributed) as is_distributed,
      (
        position('작업중' in btrim(marking_weld_a_status)) = 0 and
        (btrim(marking_weld_a_status) = '' or btrim(marking_weld_a_status) in ('작업완료', '없음') or btrim(marking_weld_a_status) like '%작업완료%') and
        position('작업중' in btrim(marking_weld_b_status)) = 0 and
        (btrim(marking_weld_b_status) = '' or btrim(marking_weld_b_status) in ('작업완료', '없음') or btrim(marking_weld_b_status) like '%작업완료%') and
        position('작업중' in btrim(marking_laser_1_status)) = 0 and
        (btrim(marking_laser_1_status) = '' or btrim(marking_laser_1_status) in ('작업완료', '없음') or btrim(marking_laser_1_status) like '%작업완료%') and
        position('작업중' in btrim(marking_laser_2_status)) = 0 and
        (btrim(marking_laser_2_status) = '' or btrim(marking_laser_2_status) in ('작업완료', '없음') or btrim(marking_laser_2_status) like '%작업완료%') and
        position('작업중' in btrim(nasa_status)) = 0 and
        (btrim(nasa_status) = '' or btrim(nasa_status) in ('작업완료', '없음') or btrim(nasa_status) like '%작업완료%') and
        position('작업중' in btrim(beveling_status)) = 0 and
        (btrim(beveling_status) = '' or btrim(beveling_status) in ('작업완료', '없음') or btrim(beveling_status) like '%작업완료%') and
        position('작업중' in btrim(main_status)) = 0 and
        (btrim(main_status) = '' or btrim(main_status) in ('작업완료', '없음') or btrim(main_status) like '%작업완료%')
      ) as is_done
    from source_rows
  )
  select
    count(*)::int,
    count(*) filter (where is_distributed)::int,
    coalesce(sum(plan_qty) filter (where is_distributed), 0)::int,
    coalesce(sum(plan_qty) filter (where is_distributed and is_done), 0)::int,
    coalesce(sum(delay_time_sec) filter (where is_distributed and not is_done), 0),
    coalesce(sum(plan_qty * process_sec) filter (where is_distributed), 0)
  into
    v_total_drawing_count,
    v_distributed_drawing_count,
    v_total_head,
    v_completed_head,
    v_pending_delay_sec,
    v_weighted_process_sec_sum
  from normalized;

  v_remaining_head := greatest(0, v_total_head - v_completed_head);

  -- Mon-Fri workday count from snapshot day to Friday of the same week.
  v_workdays_for_plan := greatest(
    1,
    (
      select count(*)
      from generate_series(
        p_snapshot_date,
        p_snapshot_date + (5 - least(extract(isodow from p_snapshot_date)::int, 5)),
        interval '1 day'
      ) d
      where extract(isodow from d)::int between 1 and 5
    )
  );

  if v_total_head > 0 then
    v_avg_process_sec := v_weighted_process_sec_sum / v_total_head;
  end if;

  v_daily_target_head := ceil(v_remaining_head::numeric / v_workdays_for_plan::numeric);
  v_required_today_sec := (v_daily_target_head * v_avg_process_sec) + (v_pending_delay_sec / v_workdays_for_plan::numeric);
  v_today_overtime_sec := least(greatest(v_required_today_sec - (9 * 3600), 0), 5 * 3600)::int;

  v_required_week_sec := (v_remaining_head * v_avg_process_sec) + v_pending_delay_sec;
  v_regular_week_sec := v_workdays_for_plan * (9 * 3600);
  v_overtime_need_week_sec := greatest(v_required_week_sec - v_regular_week_sec, 0);
  v_weekday_overtime_capacity := v_workdays_for_plan * (5 * 3600);
  v_weekly_overtime_sec := least(v_overtime_need_week_sec, v_weekday_overtime_capacity)::int;

  insert into public.daily_plan_snapshots (
    snapshot_date,
    test_date,
    weekday,
    daily_target_head,
    completed_head,
    total_head,
    remaining_head,
    today_overtime_sec,
    weekly_overtime_sec,
    distributed_drawing_count,
    total_drawing_count,
    updated_at
  )
  values (
    p_snapshot_date,
    v_test_date,
    v_weekday,
    v_daily_target_head,
    v_completed_head,
    v_total_head,
    v_remaining_head,
    v_today_overtime_sec,
    v_weekly_overtime_sec,
    v_distributed_drawing_count,
    v_total_drawing_count,
    now()
  )
  on conflict (snapshot_date)
  do update set
    test_date = excluded.test_date,
    weekday = excluded.weekday,
    daily_target_head = excluded.daily_target_head,
    completed_head = excluded.completed_head,
    total_head = excluded.total_head,
    remaining_head = excluded.remaining_head,
    today_overtime_sec = excluded.today_overtime_sec,
    weekly_overtime_sec = excluded.weekly_overtime_sec,
    distributed_drawing_count = excluded.distributed_drawing_count,
    total_drawing_count = excluded.total_drawing_count,
    updated_at = now();
end;
$$;

-- Optional: run once manually for yesterday.
-- select public.capture_daily_plan_snapshot();

-- Scheduler: 00:01 KST every day (UTC 15:01 previous day)
create extension if not exists pg_cron;

do $$
begin
  if exists (select 1 from cron.job where jobname = 'daily-plan-snapshot-kst') then
    perform cron.unschedule('daily-plan-snapshot-kst');
  end if;
end $$;

select cron.schedule(
  'daily-plan-snapshot-kst',
  '1 15 * * *',
  $$select public.capture_daily_plan_snapshot();$$
);
